# ููู ุชูููู ุงููุดุฑูุน - FUNDING.yml
# ููุณุชุฎุฏู ูุนุฑุถ ุฎูุงุฑุงุช ุงูุฏุนู ุงููุงูู ูู ูุณุชูุฏุนุงุชู ุนูู GitHub

# ูุนูููุงุช ูููุฉ:
# - ุถุน ูุฐุง ุงูููู ูู ุงููุณุงุฑ: .github/FUNDING.yml
# - ุณูุธูุฑ ุฒุฑ "Sponsor" ูู ูุณุชูุฏุนุงุชู
# - ููููู ุชูุนูู ููุตุงุช ูุชุนุฏุฏุฉ ููุฏุนู

# ==================================================
# ๐ก๏ธ ุงููุญุงุฑุจ ุงูุฑููู - asrar-mared
# Cybersecurity Professional | Digital Warrior โ๏ธ
# ==================================================

# GitHub Sponsors
# ุถุน ุงุณู ุงููุณุชุฎุฏู ุงูุฎุงุต ุจู ุนูู GitHub
github: asrar-mared

# Patreon
# ุฅุฐุง ูุงู ูุฏูู ุญุณุงุจ ุนูู Patreonุ ุถุน ุงุณู ุงููุณุชุฎุฏู
# patreon: your_patreon_username

# Open Collective
# ุฅุฐุง ููุช ุชุณุชุฎุฏู Open Collective
# open_collective: your_project_name

# Ko-fi
# ููุตุฉ ุดููุฑุฉ ููุฏุนู ุงูุณุฑูุน
# ko_fi: your_kofi_username

# Tidelift
# ูููุดุงุฑูุน ุงูููุชูุญุฉ ุงููุตุฏุฑ ุงูุงุญุชุฑุงููุฉ
# tidelift: npm/your-package-name

# Community Bridge
# ููุตุฉ Linux Foundation ููุชูููู
# community_bridge: your_project_name

# Liberapay
# ููุตุฉ ุฃูุฑูุจูุฉ ููุฏุนู ุงููุชูุฑุฑ
# liberapay: your_username

# IssueHunt
# ููุญุตูู ุนูู ุฃููุงู ููุงุจู ุญู ุงููุดุงูู
# issuehunt: your_username

# Otechie
# ููุตุฉ ููุญุตูู ุนูู ุฏุนู ููุงุจู ุงูุงุณุชุดุงุฑุงุช
# otechie: your_username

# LFX Crowdfunding
# ููุตุฉ Linux Foundation ุงูุฌุฏูุฏุฉ
# lfx_crowdfunding: your_project_name

# ุฑูุงุจุท ูุฎุตุตุฉ (ููููู ุฅุถุงูุฉ ุญุชู 4 ุฑูุงุจุท)
custom:
  - "https://nike49424.wordpress.com"
  - "https://youtube.com/shorts/wCwJpt5MvHs?si=vW6sGcA96H0n45v2"
  - "https://paypal.me/nike49424" # ุฃุถู ุฑุงุจุท PayPal ุงูุฎุงุต ุจู
  
